CREATE TABLE IF NOT EXISTS employees (
 _id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 ext TEXT NOT NULL,
 mob TEXT NOT NULL,
 age INTEGER NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS items (
 _id INTEGER PRIMARY KEY AUTOINCREMENT,
 i_time TEXT NOT NULL,
 i_value TEXT NOT NULL
);